"""Remove argument_path, Update InputArgs Table


Revision ID: 9c5ebc093ac5
Revises: 6339d9e9fc7c
Create Date: 2024-02-16 17:12:20.468663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5ebc093ac5'
down_revision: Union[str, None] = '6339d9e9fc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_args',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'FILE', name='type'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'index')
    )
    op.create_index(op.f('ix_input_args_job_id'), 'input_args', ['job_id'], unique=False)
    op.drop_column('jobs', 'argument_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('argument_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_input_args_job_id'), table_name='input_args')
    op.drop_table('input_args')
    # ### end Alembic commands ###
